### ISSUE TITLE
Использовать санитайзеры

### ISSUE THREAD

**Issue by galushin** [galushin/saga#171]
https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html

Выглядят перспективно:

- [x] address
- [x] pointer-compare
- [x] pointer-subtract
- [x] undefined (нужно ли указывать суб-опции?)
- [x] address-use-after-scope
- [x] -fsanitize=float-cast-overflow (не выполняется по умолчанию для undefined)

**Comment by galushin** [comment]
Все пункты выполнены, можно завершать
