### ISSUE TITLE
Улучшение диагностики в saga_test::check_property 

### ISSUE THREAD

**Issue by galushin** [galushin/saga#172]
- [ ] ~Автоматически захватывать сгенерированные в check_propery переменные для Catch2 через макрос CAPTURE~ - всё равно не получится захватывать имена переменных
- [x] saga_test::arbitrary - для любых контейнеров (детектировать через свойства типов)
- [ ] random_index_of - случайно выбрать индекс контейнера
- [x] random_position_of - случайно выбрать позицию в строке (может давать npos)
- [x] random_iterator_of - случайно выбрать итератор
- [x] random_subrange_of - случайный подинтервал контейнера
