### ISSUE TITLE
Доводим iid_distribution до стандартов std

### ISSUE THREAD

**Issue by galushin** [galushin/saga#9]
- [ ] Реализовать требования к распределениям (кроме того, что порождаемый тип - арифметический): https://en.cppreference.com/w/cpp/named_req/RandomNumberDistribution
- [ ] Возможность задавать дополнительные аргументы контейнера
- [ ] Как дать возможность выбирать: создание пустого плюс вставка или инициализация размером с элементами, созданным конструктором без аргументов, плюс перезапись? В настоящий момент реализован не оптимальный алгоритм - сначала компоненты контейнера инициализируются конструктором без параметров, а затем им присваиваются значения
- [ ] Проверить свойства
- [ ] Проверка статистических свойств
- [ ] Тестирование, основанное на свойствах (например, случайный выбор параметров конструктора)
- [ ] Подсказка для вывода типов

**Comment by galushin** [comment]
Архитектура распределений из <random> является не очень популярной
